# Generated by Django 3.2.4 on 2021-06-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ips',
            field=models.Field(default=[]),
        ),
        migrations.AddField(
            model_name='profile',
            name='subprofiles',
            field=models.Field(default={}),
        ),
    ]
