# Generated by Django 3.2.4 on 2021-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_nbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nBTC',
            field=models.FloatField(verbose_name=3),
        ),
    ]
