# Generated by Django 3.2.4 on 2021-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_nbtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nBTC',
            field=models.FloatField(default=7),
        ),
    ]
