# Generated by Django 3.2.4 on 2021-06-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210628_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalsupply',
            field=models.Field(default=34467.10881646146),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nBTC',
            field=models.IntegerField(default=2),
        ),
    ]
