# Generated by Django 3.2.4 on 2021-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210628_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nBTC',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalsupply',
            field=models.Field(default=310603.7229924152),
        ),
    ]
